<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://github.com/agarciadom/ttc2023-kmehr-to-fhir/trace"
    nsPrefix="tr">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//TransformationRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//SourceObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//TargetObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lazy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//Transformation" eOpposite="#//Transformation/rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//TransformationRule"
        eOpposite="#//TransformationRule/transformations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//TargetObject" eOpposite="#//TargetObject/rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//SourceObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//Transformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//TargetObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" eType="#//Transformation"
        eOpposite="#//Transformation/targets"/>
  </eClassifiers>
</ecore:EPackage>
